### ISSUE TITLE
Revision de codigo

### ISSUE THREAD

**Issue by TWebmid** [ErikSanchezRosado/Rest-NextJS#1]
Hola @ErikSanchezRosado 

### Estamos revisando tu código y aqui varios puntos positivos.
- La aplicación se realizó con nextJS
- Se utilizaron componentes por sección <Barra /> <Contenido /> <Cartas /><Caracteristicas /><Final /> lo cual hizo el codigo más legible y limpio.
- Se utilizaron fondos de background e imagenes las cuales estaban en una carpeta aparte

### Puntos a mejorar:
- Agregar una "segunda página" para utilizar Next-Router: https://nextjs.org/docs/pages/api-reference/functions/use-router
- Utilizar más tailwindcss en vez del uso de css custom sobre todo para usar flexbox: https://tailwindcss.com/docs/flex

En general ¡EXCELENTE TRABAJO! :100:

**Comment by ErikSanchezRosado** [comment]
Tnks, trataré de practicar haciendo cambios
